name: Python Application Workflow

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Installer pandas et numpy 
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy

    - name: executer un code python 
      run: python -c "import pandas; print('pandas dispo')