name: Python Application Workflow

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        node-version: 16  


    - name: install pip
      run: pip install -r requirements.txt

       
    - name: executer un code python 
      run: sudo python app.py